// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_JBSdz6TnWuwli1LJMAfNr72PrTcDMY',
    appId: '1:387550989790:web:f2f7f22a1580c66adee14f',
    messagingSenderId: '387550989790',
    projectId: 'pasarnow-e7642',
    authDomain: 'pasarnow-e7642.firebaseapp.com',
    storageBucket: 'pasarnow-e7642.firebasestorage.app',
    measurementId: 'G-35WMNWSWKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BxCx5RtCYyKVY-ShdczBE4PjOakDa2c',
    appId: '1:387550989790:android:b7e8c1c2b28ab5fedee14f',
    messagingSenderId: '387550989790',
    projectId: 'pasarnow-e7642',
    storageBucket: 'pasarnow-e7642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mvL3KlD64RsBNaz-91fLrf3kvRtQdnk',
    appId: '1:387550989790:ios:b3f5be127358469adee14f',
    messagingSenderId: '387550989790',
    projectId: 'pasarnow-e7642',
    storageBucket: 'pasarnow-e7642.firebasestorage.app',
    iosClientId: '387550989790-kofhi66t9hk1mavtqir0aerbvg7gqq77.apps.googleusercontent.com',
    iosBundleId: 'my.com.omniafoodsupply.shop',
  );
}
